### ISSUE TITLE
idle_for type error when used within method

### ISSUE THREAD

**Issue by venkivijay** [chaostoolkit/chaostoolkit-addons#9]
As per the documentation, when using `idle_for` utils, the type can be empty. But chaostoolkit expects the type to be either `action` or `probe` when used within method. Is this `idle_for` function not meant to be used within method?

**Code (method in an experiment):**
```yaml
method:
  - type: ""
    name: idle-for
    provider:
      type: python
      module: chaosaddons.utils.idle
      func: idle_for
      arguments:
        duration: 300
```

**Error:** 
```
[2022-10-18 12:40:41 INFO] Validating the experiment's syntax
[2022-10-18 12:40:41 ERROR] an activity must have a type
```
